# SPDX-FileCopyrightText: 2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

services:
  ergo-irc:
    build: .
    container_name: ergo-irc
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      MARIADB_ERGO_PASSWORD: hunter2
    ports:
      - "6667:6667/tcp"
    volumes:
      - /mnt/containers/ergo-irc:/mnt/config
